# Generated by Django 4.2.7 on 2024-03-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
